name: Update OPA executable version

on:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for OPA version and create PR if outdated
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $LatestOPARelease = Invoke-RestMethod -Uri "https://api.github.com/repos/open-policy-agent/opa/releases/latest" | Select-Object -ExpandProperty tag_name
          . .\versions.ps1
          (Get-Content -Path versions.ps1 -Raw) -replace $current_version,$latest_release | Set-Content -Path versions.ps1
          # Commit and create PR (assumes 'main' as default branch and 'update-opa-version' as PR branch)
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b opa-version-bump-$($LatestOPARelease)
          git add .
          git commit -m "Update OPA version to $LatestOPARelease"
          git push origin opa-version-bump-$($LatestOPARelease)

          gh pr create -B main -H opa-version-bump-$($LatestOPARelease) --title 'Bump OPA version to $LatestOPARelease' --body 'Created by Github action'
