name: 0Update OPA executable version

on:
  workflow_dispatch:

jobs:
  update-opa-dependency:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write 
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine if OPA update is required
        id: determine-update-required
        continue-on-error: true
        shell: powershell
        run: |
          Write-Host TESTME
          $LatestOPAVersion = Invoke-RestMethod -Uri "https://api.github.com/repos/open-policy-agent/opa/releases/latest" | Select-Object -ExpandProperty tag_name
          $OPAVersionBumpBranch = "opa-version-bump-$($LatestOPARelease)"     
          $OPABranchExists = git ls-remote --exit-code --heads origin $OPAVersionBumpBranch
          if ($LASTEXITCODE -eq 0) {
            $OPABranchExists = $true
          } else {
            $OPABranchExists = $false
          }
          echo latestopaversion=$LatestOPAVersion >> $env:GITHUB_OUTPUT
          echo opaversionbumpbranch=$OPAVersionBumpBranch >> $env:GITHUB_OUTPUT
          Write-Output "Note this step will always fail with exit code 1 when the branch does not exist. Ignore the error because that is what we want"
          exit 0
