name: 0Update OPA executable version

on:
  workflow_dispatch:

jobs:
  update-opa-dependency:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write 
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine if OPA update is required
        id: determine-update-required
        shell: powershell
        run: |
          Write-Host TESTME
          $LatestOPAVersion = Invoke-RestMethod -Uri "https://api.github.com/repos/open-policy-agent/opa/releases/latest" | Select-Object -ExpandProperty tag_name
          Write-Host $LatestOPARelease
          $OPAVersionBumpBranch = "opa-version-bump-$($LatestOPARelease)"     
          $PR = gh pr list --repo "$env:GITHUB_REPOSITORY" --head "$OPAVersionBumpBranch" --base 'master' --json title --jq 'length'
          Write-Host $PR
          WRITE-HOST fail before vars
          echo latestopaversion=$LatestOPAVersion >> $env:GITHUB_OUTPUT
          echo opaversionbumpbranch=$OPAVersionBumpBranch >> $env:GITHUB_OUTPUT
          WRITE-HOST FAIL AFTER VARS