name: 0Update OPA executable version

on:
  workflow_dispatch:

jobs:
  update-opa-dependency:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write 
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine if OPA update is required
        id: determine-update-required
        shell: powershell
        run: |
          Write-Host TESTME
          $LatestOPARelease = Invoke-RestMethod -Uri "https://api.github.com/repos/open-policy-agent/opa/releases/latest" | Select-Object -ExpandProperty tag_name
          Write-Host $LatestOPARelease
          $OPAVersionBumpBranch = "opa-version-bump-$($LatestOPARelease)"     
          WRITE-HOST fail before vars
          echo latestoparelease=$LatestOPARelease >> $env:GITHUB_OUTPUT
          echo opaversionbumpbranch=$OPAVersionBumpBranch >> $env:GITHUB_OUTPUT
          WRITE-HOST FAIL AFTER VARS
      - name: Create the OPA update PR
        run: |
          Write-Host "FAIL FIRST STEP"
          $LatestOPARelease = "${{ steps.determine-update-required.outputs.latestoparelease }}"
          $OPABranchExists = "${{ steps.determine-update-required.outputs.opaversionbumpbranch }}" 
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b $OPAVersionBumpBranch
          git add .
          git commit -m "Update OPA version to $LatestOPARelease"
          git push origin $OPAVersionBumpBranch
          gh pr create -B main -H $OPAVersionBumpBranch --title 'Bump OPA version to $LatestOPARelease' --body 'Created by Github action'