name: 0Update OPA executable version

on:
  workflow_dispatch:

jobs:
  update-opa-dependency:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write 
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Determine if OPA update is required
        id: determine-update-required
        shell: powershell
        run: |
          Write-Host TESTME
          $LatestOPARelease = Invoke-RestMethod -Uri "https://api.github.com/repos/open-policy-agent/opa/releases/latest" | Select-Object -ExpandProperty tag_name
          Write-Host $LatestOPARelease
          $OPAVersionBumpBranch = "opa-version-bump-$($LatestOPARelease)"     
          git branch --list $($OPAVersionBumpBranch)
          WRITE-HOST I GET HERE
          $OPABranchExists = git ls-remote --exit-code --heads origin $($OPAVersionBumpBranch)
          WRITE-HOST fail here somewhere
          Write-Host $OPABranchExists
          if ($OPABranchExists) {
              Write-Output "The branch already exists exists exiting workflow" 
              exit 0 
          }
          WRITE-HOST fail before vars
          WRITE-HOST FAIL AFTER VARS
