name: 0Update OPA executable version

on:
  workflow_dispatch:

jobs:
  update-opa-dependency:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write 
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine if OPA update is required
        id: determine-update-required
        continue-on-error: true
        shell: powershell
        run: |
          Write-Host TESTME
          $LatestOPAVersion = Invoke-RestMethod -Uri "https://api.github.com/repos/open-policy-agent/opa/releases/latest" | Select-Object -ExpandProperty tag_name
          Write-Host $LatestOPARelease
          $OPAVersionBumpBranch = "opa-version-bump-$($LatestOPARelease)"     
          $OPABranchExists = git ls-remote --exit-code --heads origin $OPAVersionBumpBranch
          if ($LASTEXITCODE -eq 0) {
            Write-Output "Branch exists"
          } else {
            Write-Output "Branch does not exist"
          }
          if ($OPABranchExists) {
              Write-Output "The branch already exists exists exiting workflow" 
              exit 0 
          }
          if ($LASTEXITCODE -eq 0) {
            Write-Output "Branch exists"
          } else {
            Write-Output "Branch does not exist"
          }
          WRITE-HOST fail before vars
          echo latestopaversion=$LatestOPAVersion >> $env:GITHUB_OUTPUT
          echo opaversionbumpbranch=$OPAVersionBumpBranch >> $env:GITHUB_OUTPUT
          WRITE-HOST FAIL AFTER VARS