name: 0Update OPA executable version

on:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check IF OPA version 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Write-HOST "HELLLLOOOOOO"
          Write-Output "DO YOU WORK"
          $LatestOPARelease = Invoke-RestMethod -Uri "https://api.github.com/repos/open-policy-agent/opa/releases/latest" | Select-Object -ExpandProperty tag_nam
          $OPAVersionBumpBranch = "opa-version-bump-$($LatestOPARelease)"
          . .\versions.ps1
          (Get-Content -Path versions.ps1 -Raw) -replace $current_version,$latest_release | Set-Content -Path versions.ps1
          git branch --list $($OPAVersionBumpBranch)
          $OPABranchExists = git branch --list $($OPAVersionBumpBranch)
          Write-Output "DO I BREAK HERE1"
          Write-Host $OPBranchExists
          Write-Output "DO I BREAK HERE2"
          if ($OPABranchExists) {
              Write-Host "The branch already exists exiting." 
              exit 0 
          }
          else {
                # git config --global user.email "action@github.com"
                # git config --global user.name "GitHub Action"
                # git checkout -b $OPAVersionBumpBranch
                # git add .
                # git commit -m "Update OPA version to $LatestOPARelease"
                # git push origin $OPAVersionBumpBranch
          }
      - name: Create PR
        run: |
          # gh pr create -B main -H $OPAVersionBumpBranch --title 'Bump OPA version to $LatestOPARelease' --body 'Created by Github action'
