name: This is a test job

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  update-opa-dependency:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Determine if OPA update is required
        shell: powershell
        run: |
          Write-HOST WHY